version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cafetech
    ports:
      - "5432:5432"
  
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"

  # Camunda 8 Self-Managed (Versión simplificada para dev local si no tienes cuenta Cloud)
  zeebe:
    image: camunda/zeebe:8.3.0
    ports:
      - "26500:26500"
      - "9600:9600"
    environment:
      - ZEEBE_INSECURE_CONNECTION=true